gem "sinatra", "1.0"
gem "haml", "3.0.13"
gem "octopi", "0.2.8"

group :test do
  gem "rspec", "1.3.0", :require => "spec"
  gem "mocha", "0.9.8"
  gem "rack-test", "0.5.4", :require => "rack/test"
end